### ISSUE TITLE
I don't know the startup command.

### ISSUE THREAD

**Issue by btbf** [MarcelKlammer/cardano-leader-logs#10]
node cardanoLeaderLogs.js path/to/slotLeaderLogsConfig.json epochNoneHash [optional: 1]

I don't know how to specify the epoch.
Give me an example.

**Comment by MarcelKlammer** [comment]
node cardanoLeaderLogs.js path/to/slotLeaderLogsConfig.json 171625aef5357dfccfeaeedecd5de49f71fb6e05953f2799d3ff84419dbef0ac

The current epoch is e222, see epoch-nonce.txt
If you want to see your blocks for e221:

node cardanoLeaderLogs.js path/to/slotLeaderLogsConfig.json 5ee77854fe91cc243b8d5589de3192e795f162097dba7501f8d1b0d5d7546bd5 1

**Comment by btbf** [comment]
Thank you so much!
