### ISSUE TITLE
(New Feature Request) Allow timezone to user configurable

### ISSUE THREAD

**Issue by mantispool** [MarcelKlammer/cardano-leader-logs#11]
Simple new feature request that would allow the user not to have to manually edit isSlotLeader.py every time there is a git update to the script. Add an additional field to the user's LeaderLogs.json config file for something like "TimeZone". It could default to the current 'Europe/Berlin' but the user could change the value. The changed value would then replace the hard coded text string in isSlotLeader.py at line 33. A list of valid alternative timezones can be found here: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568

**Comment by MokhFn** [comment]
That's a good feature indeed, i just submitted two pull requests to cover this feature/issue.

**Comment by MarcelKlammer** [comment]
done, thanks to @MokhFn
