### ISSUE TITLE
FYI - Missing Slots from Schedule (rounding error resolved as per pooltool.io)

### ISSUE THREAD

**Issue by kiwipool** [MarcelKlammer/cardano-leader-logs#17]
Hey Marcel

Just a heads up that there have been some missing slots in the Slot Schedule noticed by a number of SPO.

Resolved as per . . .

https://github.com/papacarp/pooltool.io/commit/d4a6e6bba7a018a6583153acc902ac9baff9a89f#diff-95a3ce53d17d7eafc171e0b29bbaaaa50df2ffed3c489982efeb3994c8168aa1

I don't have the where-with-all to do a PR today so sending you a message instead . . .

M

**Comment by btbf** [comment]
How is the update progressing?

**Comment by MarcelKlammer** [comment]
Thanks for the link above. I'm currently on vacation an this saved me a bit of time.

It's now included.

Cheers

**Comment by btbf** [comment]
I really appreciate for your prompt replying during your vacation.

**Comment by DamjanOstrelic** [comment]
I can confirm it works correctly now with the update.
