### ISSUE TITLE
The schedule is not correct.

### ISSUE THREAD

**Issue by btbf** [MarcelKlammer/cardano-leader-logs#18]
I'm using the program currently uploaded to get the schedule with the following code, but I'm getting some of the schedules wrong.

`node cardanoLeaderLogs.js path/to/slotLeaderLogsConfig.json 9b13f20f857f8afac84094d5e748f0d728df9eefec9ebf90fc61021ca9c43cb2`

However, the programs made by pooltool seem to display correctly.
When comparing the two, the sigma values do not match.

Please confirm this.

**Comment by MarcelKlammer** [comment]
Do you have the ledgerState parameter set in the config? Set it to null to generate a new ledgerState in the current epoch.

**Comment by btbf** [comment]
Sorry. I missed it in the README. Thank you very much.
