### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz

### ISSUE THREAD

**Issue by kiwipool** [MarcelKlammer/cardano-leader-logs#2]
Hey Marcel

On my Ubuntu 20.04 build I got this error:

ModuleNotFoundError: No module named 'pytz

Resolved by running the following

  python3 -m pip install pytz

You may want to add a note about this in your guide along with a reminder to export socket (if it is not in path) before running . . .

Great effort by you guys. Takes a bit of the fun and mystery away but it sure is great to get a maintenance window without playing Russian-Roulette . . .

M

**Comment by MarcelKlammer** [comment]
It's in there, right under the pip3 --version line.

**Comment by kiwipool** [comment]
Not sure how I missed that 🤷‍♂️
