### ISSUE TITLE
Error for cardano-node1.23.0

### ISSUE THREAD

**Issue by btbf** [MarcelKlammer/cardano-leader-logs#20]
Could not load ledger state from config. Trying to generate new ledgerstate.json
                  Loading: protocol parameters
(node:647100) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_pstakeSet' of undefined
    at getSigma (/home/user/git/cardano-leader-logs/ledgerUtils.js:7:102)
    at calculateLeaderLogs (/home/user/git/cardano-leader-logs/cardanoLeaderLogs.js:121:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/user/git/cardano-leader-logs/cardanoLeaderLogs.js:140:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:647100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:647100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MarcelKlammer** [comment]
For 1.23.0 getSigma needs a change.
```
  const stake           = lastEpoch ? ledger.newEs.esSnapshots._pstakeGo._stake       : ledger.newEs.esSnapshots._pstakeSet._stake
  const delegations     = lastEpoch ? ledger.newEs.esSnapshots._pstakeGo._delegations : ledger.newEs.esSnapshots._pstakeSet._delegations
```

**Comment by btbf** [comment]
Thank you for the correction.
However, there was a little discrepancy with the schedule of pooltool.io/leaderLogs

**Comment by MarcelKlammer** [comment]
The pooltool site is broken for me.

I just calculated the schedules via cncli and cardano-leader-logs and both yield the same results.

**Comment by btbf** [comment]
Thank you for the investigation.
