### ISSUE TITLE
Script finished with empty line

### ISSUE THREAD

**Issue by lunarpool** [MarcelKlammer/cardano-leader-logs#3]
Hi Marcel,

I just wanted to ask whether the output below means no leader events planned or an error, not sure if it finished successfully.

```
dusan@lunarpool:~/files$ node cardanoLeaderLogs.js ~/files/slotLeaderMoon1.json 
Network: --mainnet
Loading ledger state: /home/dusan/files/ledgerstate.json
Loading protocol parameters

dusan@lunarpool:~/files$ 
```

Many thanks
Dusan

**Comment by MarcelKlammer** [comment]
Hi Dusan,

yes, no output means no blocks scheduled.

Will need to add more logs to make it more clear.

**Comment by MarcelKlammer** [comment]
Someone did just that. :)
