### ISSUE TITLE
AttributeError: /usr/local/lib/libsodium.so: undefined symbol: crypto_vrf_ietfdraft03_proofbytes

### ISSUE THREAD

**Issue by sp33dy** [MarcelKlammer/cardano-leader-logs#6]
Hi there,

It's Crazy Career (VEGAS pool) here.

Having followed the instructions, I (as well as another pool operator) are getting this error:

`process args: [ '/usr/bin/node',
  '*edited*/cardanoLeaderLogs.js',
  '*edited*/slotLeaderLogsConfig.json',
  '171625aef5357dfccfeaeedecd5de49f71fb6e05953f2799d3ff84419dbef0ac' ]
replay last epoch false
Network: --mainnet
Loading ledger state: *edited*/ledgerstate.json
Could not load ledger state from config. Trying to generate new ledgerstate.json
Loading protocol parameters
active stake: 3399243440126
total stake:  16371244779824320
firstSlotOfEpoch 10540800
sigma 0.0002076350018488012
{ Error: Command failed: python3 ./isSlotLeader.py --first-slot-of-epoch 10540800 --epoch-nonce 171625aef5357dfccfeaeedecd5de49f71fb6e05953f2799d3ff84419dbef0ac --vrf-skey *edited* --sigma 0.0002076350018488012 --d 0.6 --epoch-length 432000 --active-slots-coeff 0.05 --libsodium-binary /usr/local/lib/libsodium.so
Traceback (most recent call last):
  File "./isSlotLeader.py", line 98, in <module>
    slotLeader = isSlotLeader(slot,activeSlotsCoeff,sigma,eta0,poolVrfSkey)
  File "./isSlotLeader.py", line 85, in isSlotLeader
    cert=vrfEvalCertified(seed,tpraosCanBeLeaderSignKeyVRFb)
  File "./isSlotLeader.py", line 55, in vrfEvalCertified
    proof = create_string_buffer(libsodium.crypto_vrf_ietfdraft03_proofbytes())
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libsodium.so: undefined symbol: crypto_vrf_ietfdraft03_proofbytes

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'python3 ./isSlotLeader.py --first-slot-of-epoch 10540800 --epoch-nonce 171625aef5357dfccfeaeedecd5de49f71fb6e05953f2799d3ff84419dbef0ac --vrf-skey *edited* --sigma 0.0002076350018488012 --d 0.6 --epoch-length 432000 --active-slots-coeff 0.05 --libsodium-binary /usr/local/lib/libsodium.so' }
Traceback (most recent call last):
  File "./isSlotLeader.py", line 98, in <module>
    slotLeader = isSlotLeader(slot,activeSlotsCoeff,sigma,eta0,poolVrfSkey)
  File "./isSlotLeader.py", line 85, in isSlotLeader
    cert=vrfEvalCertified(seed,tpraosCanBeLeaderSignKeyVRFb)
  File "./isSlotLeader.py", line 55, in vrfEvalCertified
    proof = create_string_buffer(libsodium.crypto_vrf_ietfdraft03_proofbytes())
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libsodium.so: undefined symbol: crypto_vrf_ietfdraft03_proofbytes
`

Any ideas what might be wrong?

Can be got directly here: https://t.me/VEGAS_ADA_POOL if it helps to chat.

**Comment by MarcelKlammer** [comment]
You are using the wrong version of libsodium.

Build the IOG version with commit 66f017f1 as you would do to compile your cardano-node binary:
https://github.com/input-output-hk/libsodium

**Comment by sp33dy** [comment]
Ah crap! Could you pop that into the front page? Many thanks!

**Comment by sp33dy** [comment]
Still same issue, can you confirm I'm not missing a step:

- `git clone  https://github.com/input-output-hk/libsodium.git`
- `./configure
make && make check
sudo make install
`

I can confirm the libsodium is in the /usr/local/lib folder as expected. 

Sorry Marcel if it's something stupid that I'm doing. Just can't see what.

**Comment by MarcelKlammer** [comment]
git checkout 66f017f1

?

**Comment by sp33dy** [comment]
This is where my experience with git lets me down. If I clone the IOHK libsodium repository, it configures and makes. However, if I checkout 66f017f1, then that switches the head to the branch, but nothing will make. Do I have to merge these some how??

**Comment by MarcelKlammer** [comment]
You clone the repo. You checkout the specific commit. Then you configure, make, make install

- git clone https://github.com/input-output-hk/libsodium.git
- git checkout 66f017f1
- ./configure
- make && make check
- sudo make install

**Comment by sp33dy** [comment]
`crazy@base:~/Node/leaderLogs$ git clone https://github.com/input-output-hk/libsodium.git
Cloning into 'libsodium'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 30154 (delta 0), reused 0 (delta 0), pack-reused 30153
Receiving objects: 100% (30154/30154), 7.63 MiB | 7.03 MiB/s, done.
Resolving deltas: 100% (17747/17747), done.
crazy@base:~/Node/leaderLogs$ cd libsodium/
crazy@base:~/Node/leaderLogs/libsodium$ ls
aclocal.m4    builds        dist-build                   libsodium.vcxproj          Makefile.am      regen-msvc
appveyor.yml  ChangeLog     lgtm.yml                     libsodium.vcxproj.filters  Makefile.in      src
AUTHORS       configure     libsodium.pc.in              LICENSE                    msvc-scripts     test
autogen.sh    configure.ac  libsodium.sln                logo.png                   packaging        THANKS
build-aux     contrib       libsodium-uninstalled.pc.in  m4                         README.markdown
crazy@base:~/Node/leaderLogs/libsodium$ git checkout 66f017f1
Note: switching to '66f017f1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 66f017f1 Fix issue when building VRF tests with g++
crazy@base:~/Node/leaderLogs/libsodium$ ls
appveyor.yml         builds        lgtm.yml                     libsodium.vcxproj          m4            README.markdown  THANKS
AUTHORS              ChangeLog     libsodium.pc.in              libsodium.vcxproj.filters  Makefile.am   regen-msvc
autogen.sh           configure.ac  libsodium.sln                LICENSE                    msvc-scripts  src
azure-pipelines.yml  dist-build    libsodium-uninstalled.pc.in  logo.png                   packaging     test
crazy@base:~/Node/leaderLogs/libsodium$ ./configure
bash: ./configure: No such file or directory
crazy@base:~/Node/leaderLogs/libsodium$ 

`

It's got to be me and I don't want to annoy. I just don't see what's going on. If I look in the directories before and after the check out, the configure folder is removed. Do I need to use another flag???

**Comment by sp33dy** [comment]
I'm AN IDIOT! I'd not noticed the error TELLING me LIBTOOL is not installed, if I run autogen.sh. That then enables me to run the configure and make. Many many thanks and HUGE sorry for wasting your time.

**Comment by MarcelKlammer** [comment]
Let's leave this issue open for a while, so others may find the same solution :)
