### ISSUE TITLE
Odd-length string

### ISSUE THREAD

**Issue by queiroz** [MarcelKlammer/cardano-leader-logs#7]
Apparently, python is complaining about:

```
h.update(slot.to_bytes(8,byteorder='big') + binascii.unhexlify(eta0))
binascii.Error: Odd-length string
```
Python 3.6.8.

**Comment by MarcelKlammer** [comment]
I guess you missed 1 character of the epoch nonce when you copied it.

**Comment by queiroz** [comment]
Yeap was missing the hash, thanks anyways.
